model_list:
  - model_name: "anthropic/*"
    litellm_params:
      model: "anthropic/*"
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: "together_ai/*"
    litellm_params:
      model: "together_ai/*"
      api_key: os.environ/TOGETHERAI_API_KEY
      api_base: "https://api.together.xyz/v1"

litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

router_settings:
  model_group_alias:
    { "llama-3.1-8b-instruct-turbo": "together_ai/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo" }
